// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/realworld/realworld.proto

package com_example_service_realworld

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerPush_Type int32

const (
	ServerPush_HEARTBEAT    ServerPush_Type = 0
	ServerPush_PUBLISH_NOTE ServerPush_Type = 1
)

var ServerPush_Type_name = map[int32]string{
	0: "HEARTBEAT",
	1: "PUBLISH_NOTE",
}

var ServerPush_Type_value = map[string]int32{
	"HEARTBEAT":    0,
	"PUBLISH_NOTE": 1,
}

func (x ServerPush_Type) String() string {
	return proto.EnumName(ServerPush_Type_name, int32(x))
}

func (ServerPush_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9257436109765583, []int{10, 0}
}

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257436109765583, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257436109765583, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	NumInt32             int32    `protobuf:"varint,2,opt,name=num_int32,json=numInt32,proto3" json:"num_int32,omitempty"`
	NumInt64             int64    `protobuf:"varint,3,opt,name=num_int64,json=numInt64,proto3" json:"num_int64,omitempty"`
	NumFloat             float32  `protobuf:"fixed32,4,opt,name=num_float,json=numFloat,proto3" json:"num_float,omitempty"`
	NumDouble            float64  `protobuf:"fixed64,5,opt,name=num_double,json=numDouble,proto3" json:"num_double,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257436109765583, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetNumInt32() int32 {
	if m != nil {
		return m.NumInt32
	}
	return 0
}

func (m *Response) GetNumInt64() int64 {
	if m != nil {
		return m.NumInt64
	}
	return 0
}

func (m *Response) GetNumFloat() float32 {
	if m != nil {
		return m.NumFloat
	}
	return 0
}

func (m *Response) GetNumDouble() float64 {
	if m != nil {
		return m.NumDouble
	}
	return 0
}

type StreamingRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257436109765583, []int{3}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257436109765583, []int{4}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257436109765583, []int{5}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257436109765583, []int{6}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type PublishReq struct {
	PublishNote          *PublishNote `protobuf:"bytes,1,opt,name=publish_note,json=publishNote,proto3" json:"publish_note,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PublishReq) Reset()         { *m = PublishReq{} }
func (m *PublishReq) String() string { return proto.CompactTextString(m) }
func (*PublishReq) ProtoMessage()    {}
func (*PublishReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257436109765583, []int{7}
}

func (m *PublishReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishReq.Unmarshal(m, b)
}
func (m *PublishReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishReq.Marshal(b, m, deterministic)
}
func (m *PublishReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishReq.Merge(m, src)
}
func (m *PublishReq) XXX_Size() int {
	return xxx_messageInfo_PublishReq.Size(m)
}
func (m *PublishReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishReq.DiscardUnknown(m)
}

var xxx_messageInfo_PublishReq proto.InternalMessageInfo

func (m *PublishReq) GetPublishNote() *PublishNote {
	if m != nil {
		return m.PublishNote
	}
	return nil
}

type PublishResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishResp) Reset()         { *m = PublishResp{} }
func (m *PublishResp) String() string { return proto.CompactTextString(m) }
func (*PublishResp) ProtoMessage()    {}
func (*PublishResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257436109765583, []int{8}
}

func (m *PublishResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResp.Unmarshal(m, b)
}
func (m *PublishResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResp.Marshal(b, m, deterministic)
}
func (m *PublishResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResp.Merge(m, src)
}
func (m *PublishResp) XXX_Size() int {
	return xxx_messageInfo_PublishResp.Size(m)
}
func (m *PublishResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResp.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResp proto.InternalMessageInfo

type Heartbeat struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257436109765583, []int{9}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ServerPush struct {
	T                    ServerPush_Type `protobuf:"varint,1,opt,name=t,proto3,enum=com.example.service.realworld.ServerPush_Type" json:"t,omitempty"`
	PublishNote          *PublishNote    `protobuf:"bytes,2,opt,name=publish_note,json=publishNote,proto3" json:"publish_note,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ServerPush) Reset()         { *m = ServerPush{} }
func (m *ServerPush) String() string { return proto.CompactTextString(m) }
func (*ServerPush) ProtoMessage()    {}
func (*ServerPush) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257436109765583, []int{10}
}

func (m *ServerPush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerPush.Unmarshal(m, b)
}
func (m *ServerPush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerPush.Marshal(b, m, deterministic)
}
func (m *ServerPush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerPush.Merge(m, src)
}
func (m *ServerPush) XXX_Size() int {
	return xxx_messageInfo_ServerPush.Size(m)
}
func (m *ServerPush) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerPush.DiscardUnknown(m)
}

var xxx_messageInfo_ServerPush proto.InternalMessageInfo

func (m *ServerPush) GetT() ServerPush_Type {
	if m != nil {
		return m.T
	}
	return ServerPush_HEARTBEAT
}

func (m *ServerPush) GetPublishNote() *PublishNote {
	if m != nil {
		return m.PublishNote
	}
	return nil
}

type PublishNote struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishNote) Reset()         { *m = PublishNote{} }
func (m *PublishNote) String() string { return proto.CompactTextString(m) }
func (*PublishNote) ProtoMessage()    {}
func (*PublishNote) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257436109765583, []int{11}
}

func (m *PublishNote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishNote.Unmarshal(m, b)
}
func (m *PublishNote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishNote.Marshal(b, m, deterministic)
}
func (m *PublishNote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishNote.Merge(m, src)
}
func (m *PublishNote) XXX_Size() int {
	return xxx_messageInfo_PublishNote.Size(m)
}
func (m *PublishNote) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishNote.DiscardUnknown(m)
}

var xxx_messageInfo_PublishNote proto.InternalMessageInfo

func (m *PublishNote) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PublishNote) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterEnum("com.example.service.realworld.ServerPush_Type", ServerPush_Type_name, ServerPush_Type_value)
	proto.RegisterType((*Message)(nil), "com.example.service.realworld.Message")
	proto.RegisterType((*Request)(nil), "com.example.service.realworld.Request")
	proto.RegisterType((*Response)(nil), "com.example.service.realworld.Response")
	proto.RegisterType((*StreamingRequest)(nil), "com.example.service.realworld.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "com.example.service.realworld.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "com.example.service.realworld.Ping")
	proto.RegisterType((*Pong)(nil), "com.example.service.realworld.Pong")
	proto.RegisterType((*PublishReq)(nil), "com.example.service.realworld.PublishReq")
	proto.RegisterType((*PublishResp)(nil), "com.example.service.realworld.PublishResp")
	proto.RegisterType((*Heartbeat)(nil), "com.example.service.realworld.Heartbeat")
	proto.RegisterType((*ServerPush)(nil), "com.example.service.realworld.ServerPush")
	proto.RegisterType((*PublishNote)(nil), "com.example.service.realworld.PublishNote")
}

func init() {
	proto.RegisterFile("proto/realworld/realworld.proto", fileDescriptor_9257436109765583)
}

var fileDescriptor_9257436109765583 = []byte{
	// 583 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x4e, 0xdb, 0x4c,
	0x10, 0xcd, 0x26, 0xe1, 0xc7, 0x03, 0x7c, 0xca, 0xb7, 0xaa, 0xaa, 0x28, 0x88, 0x36, 0xdd, 0x4a,
	0xc5, 0x70, 0x61, 0x50, 0x40, 0xf4, 0xa6, 0x37, 0x40, 0xa9, 0x40, 0x2a, 0x34, 0xda, 0xa4, 0x17,
	0x6d, 0x2f, 0x90, 0x6d, 0x06, 0x63, 0x61, 0xef, 0x1a, 0xef, 0x9a, 0xc2, 0x6b, 0xf4, 0x55, 0xfa,
	0x06, 0x7d, 0x89, 0xbe, 0x4e, 0xe5, 0xb5, 0x9d, 0xa0, 0xb6, 0xc2, 0x91, 0x7a, 0x37, 0x27, 0xe7,
	0xcc, 0x64, 0xce, 0xce, 0x91, 0xe1, 0x79, 0x92, 0x4a, 0x2d, 0xb7, 0x52, 0x74, 0xa3, 0xaf, 0x32,
	0x8d, 0x2e, 0xa6, 0x95, 0x63, 0x18, 0xba, 0xe6, 0xcb, 0xd8, 0xc1, 0x3b, 0x37, 0x4e, 0x22, 0x74,
	0x14, 0xa6, 0xb7, 0xa1, 0x8f, 0xce, 0x44, 0xc4, 0x56, 0x61, 0xe1, 0x14, 0x95, 0x72, 0x03, 0xa4,
	0x1d, 0x68, 0x29, 0xf7, 0xbe, 0x4b, 0xfa, 0xc4, 0xb6, 0x78, 0x5e, 0xb2, 0x2d, 0x58, 0xe0, 0x78,
	0x93, 0xa1, 0xd2, 0x94, 0x42, 0x5b, 0xb8, 0x31, 0x96, 0xac, 0xa9, 0xf3, 0x06, 0x37, 0xc0, 0x6e,
	0xb3, 0x4f, 0xec, 0x39, 0x9e, 0x97, 0xec, 0x1b, 0x81, 0x45, 0x8e, 0x2a, 0x91, 0x42, 0x19, 0x3a,
	0x56, 0x41, 0x35, 0x2f, 0x56, 0x01, 0x5d, 0x05, 0x4b, 0x64, 0xf1, 0x79, 0x28, 0xf4, 0xce, 0xa0,
	0x6c, 0x5b, 0x14, 0x59, 0x7c, 0x92, 0xe3, 0x07, 0xe4, 0xde, 0x6e, 0xb7, 0xd5, 0x27, 0x76, 0xab,
	0x22, 0xf7, 0x76, 0x2b, 0xf2, 0x32, 0x92, 0xae, 0xee, 0xb6, 0xfb, 0xc4, 0x6e, 0x1a, 0xf2, 0x5d,
	0x8e, 0xe9, 0x1a, 0x40, 0x4e, 0x5e, 0xc8, 0xcc, 0x8b, 0xb0, 0x3b, 0xd7, 0x27, 0x36, 0xe1, 0xb9,
	0xfc, 0xad, 0xf9, 0x81, 0xd9, 0xd0, 0x19, 0xe9, 0x14, 0xdd, 0x38, 0x14, 0x41, 0x65, 0xe7, 0x09,
	0xcc, 0xf9, 0x32, 0x13, 0xda, 0x6c, 0xd7, 0xe2, 0x05, 0x60, 0x1b, 0xf0, 0xff, 0x03, 0x65, 0x69,
	0xe3, 0xef, 0xd2, 0x67, 0xd0, 0x1e, 0x86, 0x22, 0xa0, 0x4f, 0x61, 0x5e, 0xe9, 0x54, 0x5e, 0x63,
	0x49, 0x97, 0xc8, 0xf0, 0xf2, 0x11, 0xfe, 0x0b, 0xc0, 0x30, 0xf3, 0xa2, 0x50, 0x5d, 0x71, 0xbc,
	0xa1, 0xa7, 0xb0, 0x9c, 0x14, 0xe8, 0x5c, 0x48, 0x5d, 0x68, 0x97, 0x06, 0x9b, 0xce, 0xa3, 0xb7,
	0x73, 0xca, 0x01, 0x67, 0x52, 0x23, 0x5f, 0x4a, 0xa6, 0x80, 0xad, 0xc0, 0xd2, 0x64, 0xb8, 0x4a,
	0xd8, 0x0b, 0xb0, 0x8e, 0xd1, 0x4d, 0xb5, 0x87, 0xae, 0x71, 0xae, 0xe5, 0x35, 0x8a, 0xf2, 0x2e,
	0x05, 0x60, 0x3f, 0x08, 0xc0, 0x08, 0xd3, 0x5b, 0x4c, 0x87, 0x99, 0xba, 0xa2, 0x6f, 0x80, 0x14,
	0x7e, 0xff, 0x1b, 0x38, 0x35, 0x4b, 0x4c, 0xbb, 0x9c, 0xf1, 0x7d, 0x82, 0x9c, 0xe8, 0x3f, 0xdc,
	0x34, 0xff, 0xcd, 0xcd, 0x3a, 0xb4, 0xf3, 0xc9, 0x74, 0x05, 0xac, 0xe3, 0xa3, 0x7d, 0x3e, 0x3e,
	0x38, 0xda, 0x1f, 0x77, 0x1a, 0xb4, 0x03, 0xcb, 0xc3, 0x8f, 0x07, 0xef, 0x4f, 0x46, 0xc7, 0xe7,
	0x67, 0x1f, 0xc6, 0x47, 0x1d, 0xc2, 0x5e, 0x4f, 0x6c, 0xe7, 0x7d, 0x85, 0xd3, 0x24, 0xf4, 0xa7,
	0x4e, 0x93, 0xd0, 0xcf, 0x83, 0xac, 0xf1, 0x4e, 0x9b, 0xa5, 0x2c, 0x6e, 0xea, 0xc1, 0xf7, 0x26,
	0x58, 0xbc, 0x5a, 0x84, 0x7e, 0x82, 0xf6, 0xa1, 0x1b, 0x45, 0xf4, 0x55, 0xcd, 0xc2, 0x65, 0x96,
	0x7a, 0xeb, 0xb5, 0xba, 0x22, 0x49, 0xac, 0x41, 0x25, 0xcc, 0x17, 0x01, 0xa3, 0x5b, 0x75, 0xcf,
	0xfa, 0x5b, 0x62, 0x7b, 0xdb, 0xb3, 0x37, 0x54, 0x7f, 0xb7, 0x4d, 0xe8, 0x67, 0x58, 0xcc, 0x63,
	0x6a, 0xa2, 0xf8, 0xb2, 0xee, 0x00, 0xa1, 0x08, 0x7a, 0xb5, 0x22, 0x29, 0x02, 0xd6, 0xb0, 0xc9,
	0x36, 0x19, 0xfc, 0x24, 0x60, 0x1d, 0x46, 0x99, 0x77, 0x25, 0x33, 0x85, 0xd4, 0x83, 0x85, 0xf2,
	0xf1, 0xe9, 0xc6, 0x6c, 0x97, 0xe6, 0x78, 0xd3, 0xdb, 0x9c, 0x55, 0xaa, 0x12, 0xd6, 0xa0, 0x97,
	0x60, 0x8d, 0x32, 0x4f, 0xf9, 0x69, 0xe8, 0x21, 0xb5, 0x6b, 0x5a, 0x27, 0x91, 0xef, 0x6d, 0xcc,
	0x1c, 0xe1, 0xc2, 0x99, 0x37, 0x6f, 0x3e, 0x9d, 0x3b, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3a,
	0x6f, 0xfa, 0x34, 0x5d, 0x05, 0x00, 0x00,
}
